create table users
(
    id            integer primary key generated by default as identity,
    username      text not null unique,
    password_hash text not null
);

create table coordinates
(
    id integer generated by default as identity primary key,
    x  double precision not null,
    y  double precision not null
);

create table location
(
    id   integer generated by default as identity primary key,
    x    integer      not null,
    y    integer      not null,
    z    integer      not null,
    name varchar(255) not null
);

create table address
(
    id      integer generated by default as identity primary key,
    steet   varchar(255) not null,
    zipCode varchar(255) not null check (length(zipCode) > 3),
    town    integer references location (id)
);
create type workersPositions as enum ('LABORER','ENGINEER','HEAD_OF_DEPARTMENT',
    'LEAD_DEVELOPER',
    'BAKER');

create table organization
(
    id              integer primary key generated by default as identity,
    fullname        varchar(255)     not null
        unique,
    employeescount  integer          not null,
    annualturnover  double precision not null,
    postalAddress integer references address(id)
);

create table worker
(
    id                    integer generated by default as identity primary key,
    name                  varchar(255)     not null,
    coordinates_id integer references coordinates(id),
    creation_date         date             not null,
    salary                integer          not null,
    start_date            date             not null,
    end_date              timestamp,
    workersPosition workersPositions not null ,
    organization_id integer references organization(id),
    user_id integer references users(id)
);

