create table users
(
    id integer primary key generated by default as identity ,
    username      text not null unique ,
    password_hash text not null
);



create table organization
(
    id integer primary key generated by default as identity ,
    fullname        varchar(255)     not null
        unique ,
    employeescount  integer          not null,
    annualturnover  double precision not null,
    address_street  varchar(255)     not null,
    address_zipcode varchar(255)     not null,
    address_town    varchar(255)     not null,
    address_x       integer          not null,
    address_y       integer          not null,
    address_z       integer          not null
);


create table worker
(
    id                    integer generated by default as identity primary key,
    name                  varchar(255)     not null,
    coordinates_x         double precision not null,
    coordinates_y         double precision not null,
    creation_date         date             not null,
    salary                integer          not null,
    start_date            date             not null,
    end_date              timestamp,
    position              varchar(255)     not null,
    organization_fullname varchar
        references organization (fullname),
    username              varchar(255)     not null
        references users (username)
);